'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("crsButton.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _New() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_New", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property accept() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("accept", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property accept_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("accept_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_combo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_combo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_combo_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_combo_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property allowances() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("allowances", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property allowances_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("allowances_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property aquire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aquire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property aquire_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aquire_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Automate_settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Automate_settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Automate_settings_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Automate_settings_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backup_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backup_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property batch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("batch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property batch_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("batch_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancel_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property capture_photo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("capture_photo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property capture_photo_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("capture_photo_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close2_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close2_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property committee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("committee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property committee_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("committee_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property contact() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("contact", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property contact_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("contact_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property contributions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("contributions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property contributions_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("contributions_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property courses() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("courses", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property courses_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("courses_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deductions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deductions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deductions_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deductions_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property export() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("export", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property export_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("export_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property find() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("find", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property find_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("find_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property first() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("first", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property first_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("first_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property flip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property flip_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flip_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property import() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("import", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property import_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("import_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property individual() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("individual", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property individual_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("individual_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property last() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("last", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property last_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("last_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loans() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loans", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loans_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loans_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property login_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property New_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property next_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ok_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property photo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("photo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property photo_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("photo_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property prev() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prev", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property prev_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prev_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print_preview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_preview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print_preview_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_preview_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property qualification() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("qualification", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property qualification_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("qualification_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property redo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property redo_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redo_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property remove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("remove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property remove_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("remove_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property report() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("report", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property report_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("report_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property restore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("restore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property restore_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("restore_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property startprocessing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("startprocessing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property startprocessing_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("startprocessing_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stopprocessing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stopprocessing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stopprocessing_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stopprocessing_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property test_connection() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("test_connection", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property test_connection_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("test_connection_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to accept
        '''add
        '''add_combo
        '''allowances
        '''aquire
        '''Automate_settings
        '''backup
        '''batch
        '''cancel
        '''capture_photo
        '''close
        '''close2
        '''committee
        '''contact
        '''contributions
        '''courses
        '''deductions
        '''edit
        '''export
        '''find
        '''first
        '''flip
        '''import
        '''individual
        '''last
        '''loans
        '''login
        '''New
        '''next
        '''ok
        '''photo
        '''prev
        '''print
        '''print_preview
        '''qualification
        '''redo
        '''remove
        '''report
        '''restore
        '''save
        '''search
        '''startprocessing
        '''stopprocessing
        '''test_connection
        '''undo
        '''view
        '''zoom
        '''.
        '''</summary>
        Friend ReadOnly Property txtNames() As String
            Get
                Return ResourceManager.GetString("txtNames", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property undo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("undo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property undo_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("undo_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property view() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property view_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zoom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zoom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zoom_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zoom_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
